apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-criar-contatos-persistent-volume-claim
  labels:
    app: consumer-criar-contatos
    tier: backend
  annotations:
    description: "Claim para acessar o volume persistente do microsserviço consumer-criar-contatos"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
